INSERT INTO store (name, opening, closing, location, review, imagepath) VALUES ('Parachute', 6, 1, 'Hammersmith', 'Poor', 'Hammersmith');
INSERT INTO store (name, opening, closing, location, review, imagepath) VALUES ('One Pound Store' , 7, 23, 'White City', 'Good', 'whitecity');
INSERT INTO store (name, opening, closing, location, review, imagepath) VALUES ('Ealing Food and Wine', 18, 7, 'Ealing', 'Satisfactory', 'ealing');

INSERT INTO item (name, price, rating, category, description, imagepath, store_id) VALUES ('Warbutons Toastie', 1.25, 3, 'Bakery', 'Thick Sliced White Bread', 'bread', 2);
INSERT INTO item (name, price, rating, category, description, imagepath, store_id) VALUES ('Cinnamon Swirls', 0.6, 3, 'Bakery', 'Danish pastry whirls with cinnamon remonce between layers of pastry, topped with glaze', 'swirls', 1);
INSERT INTO item (name, price, rating, category, description, imagepath, store_id) VALUES ('Bake At Home Baguette', 0.6, 4, 'Bakery', '2 part baked white baguettes', 'baguettes', 1);
INSERT INTO item (name, price, rating, category, description, imagepath, store_id) VALUES ('Chocolate Iced Ring Donuts', 1.25, 3, 'Bakery', 'Chocolate iced doughnuts topped with chocolate flavour sugar strands', 'donuts', 3);
insert into item (name, price, rating, category, description, imagepath, store_id) values ('Stone Baked Pitta Bread', 2.75, 3, 'Bakery', 'Toast Me!', 'pitta', 2);
insert into item (name, price, rating, category, description, imagepath, store_id) values ('Warburtons White Rolls', 1.7, 4, 'Bakery', '12 Sliced White Rolls', 'rolls', 1);
insert into item (name, price, rating, category, description, imagepath, store_id) values ('Lyles Golden Syrup 454g', 1.55, 5, 'Bakery', 'Partially Inverted Refiners Syrup', 'syrup', 1);
insert into item (name, price, rating, category, description, imagepath, store_id) values ('Betty Crocker Velvety Vanilla Cake Mix 425g', 2.5, 5, 'Bakery', 'Vanilla Flavoured Cake Mix.', 'cakemix', 3);
insert into item (name, price, rating, category, description, imagepath, store_id) values ('Victoria Sponge Cake', 3, 4, 'Bakery', 'Sponge sandwiched with buttercream and raspberry jam, topped with a dusting of sugar', 'cake', 3);
insert into item (name, price, rating, category, description, imagepath, store_id) values ('Schweppes Tonic Water 1L', 19.7, 1, 'Drink', 'Sparkling Soft Drink with Quinine with Sugar and Sweetener', 'tonic', 3);
insert into item (name, price, rating, category, description, imagepath, store_id) values ('Cono Sur Bicicleta Viognier 75cl', 7, 3, 'Drink', 'White wine', 'whitewine', 2);
insert into item (name, price, rating, category, description, imagepath, store_id) values ('Malibu Piña Colada Pre-Mixed Can 250ml', 1.65, 1, 'Drink', 'Coconut and Pineapple Flavour Mixed Drink with Caribbean Rum', 'pinacolada', 1);
insert into item (name, price, rating, category, description, imagepath, store_id) values ('Fete Bordeaux Merlot 75cl', 7.31, 3, 'Drink', 'Red Wine', 'redwine', 2);
INSERT INTO item (name, price, rating, category, description, imagepath, store_id) VALUES ('Coca Cola 1.25L', 0.99, 4, 'Drink', 'Carbonated soft drink', 'cocacola', 2);
INSERT INTO item (name, price, rating, category, description, imagepath, store_id) VALUES ('Yorkshire Tea Bags x240', 4, 5, 'Drink', 'Black Tea', 'tea', 1);
INSERT INTO item (name, price, rating, category, description, imagepath, store_id) VALUES ('Nescafe Original', 8, 3, 'Drink', 'Its the perfect bold flavour you know and love, but now with a smoother taste', 'coffee', 3);
INSERT INTO item (name, price, rating, category, description, imagepath, store_id) VALUES ('Large Whole Milk', 1.60, 4, 'Dairy', '6 Pint Milk', 'largemilk', 2);
INSERT INTO item (name, price, rating, category, description, imagepath, store_id) VALUES ('Clover Spread 500g', 1.60, 4, 'Dairy', '64% fat spread with buttermilk', 'butter', 3);
INSERT INTO item (name, price, rating, category, description, imagepath, store_id) VALUES ('Mozzarella Cheese 150g', 1.60, 4, 'Dairy', 'Mozzarella cheese made with pasterurised cows milk, packed in brine', 'mozzarellacheese', 1);
insert into item (name, price, rating, category, description, imagepath, store_id) values ('Large Soy Milk', 1.55, 4, 'Dairy', 'Organic Soy Milk', 'soymilk', 2);
insert into item (name, price, rating, category, description, imagepath, store_id) values ('Greek Yoghurt', 1.20, 4, 'Dairy', 'Greek style natural yogurt', 'greek', 2);
insert into item (name, price, rating, category, description, imagepath, store_id) values ('Häagen-Dazs Ice Cream Vanilla 460ml', 4, 4, 'Dairy', 'Vanilla ice cream', 'icecream', 2);
insert into item (name, price, rating, category, description, imagepath, store_id) values ('Brie De Meaux', 3.5, 2, 'Dairy', 'Unpasteurised mould ripened cheese', 'brie', 3);
insert into item (name, price, rating, category, description, imagepath, store_id) values ('Skimmed Milk 2 pint', 1.30, 1, 'Dairy', 'Organic pasteurised skimmed milk', 'skimmedmilk', 1);
insert into item (name, price, rating, category, description, imagepath, store_id) values ('Fairtrade Bananas Loose', 0.78, 2, 'Fruit', 'Fairtade Bananas', 'banana', 3);
insert into item (name, price, rating, category, description, imagepath, store_id) values ('Ripe Pears x4', 2, 3, 'Fruit', 'Pears Class I', 'pears', 1);
insert into item (name, price, rating, category, description, imagepath, store_id) values ('Peeled Plum Tomatoes 4x400g', 2.20, 3, 'Fruit', 'Peeled Plum Tomatoes in Rich Tomato Juice', 'tomatoes', 3);
insert into item (name, price, rating, category, description, imagepath, store_id) values ('Raspberries 150g', 2, 4, 'Fruit', 'Raspberries', 'raspberries', 1);
insert into item (name, price, rating, category, description, imagepath, store_id) values ('Strawberries 400g', 3.5, 5, 'Fruit', 'Strawberries Class I', 'strawberries', 2);
insert into item (name, price, rating, category, description, imagepath, store_id) values ('Tasty Gala Apples x6', 1, 3, 'Fruit', 'Apples Class II', 'apples', 2);
insert into item (name, price, rating, category, description, imagepath, store_id) values ('Mango 250g', 1.6, 4, 'Fruit', 'Mango Chunks', 'mangoes', 2);
insert into item (name, price, rating, category, description, imagepath, store_id) values ('Blueberries 500g', 4, 4, 'Fruit', 'Blueberries Class I', 'blueberries', 2);
insert into item (name, price, rating, category, description, imagepath, store_id) values ('Tangerines 600g', 1.35, 4, 'Fruit', 'Tangerines Class I', 'tangerines', 2);
insert into item (name, price, rating, category, description, imagepath, store_id) values ('Celery', 0.49, 4, 'Vegetable', 'Celery', 'celery', 2);
insert into item (name, price, rating, category, description, imagepath, store_id) values ('Broccoli Loose', 1.40, 3, 'Vegetable', 'Broccoli', 'broccoli', 2);
insert into item (name, price, rating, category, description, imagepath, store_id) values ('Red Kidney Beans 400g', 0.75, 4, 'Vegetable', 'Red Kidney Beans in Water', 'kidneybeans', 2);
insert into item (name, price, rating, category, description, imagepath, store_id) values ('Beansprouts 300g', 0.75, 3, 'Vegetable', 'Beansprouts', 'beansprouts', 2);
insert into item (name, price, rating, category, description, imagepath, store_id) values ('Red Cabbage', 0.59, 2, 'Vegetable', 'Red Cabbage', 'cabbage', 2);
insert into item (name, price, rating, category, description, imagepath, store_id) values ('Large Flat Mushrooms 250g', 1, 4, 'Vegetable', 'Large Flat White Mushrooms', 'mushrooms', 3);
insert into item (name, price, rating, category, description, imagepath, store_id) values ('Romaine Lettuce Hearts, Twin Pack x2', 1, 3, 'Vegetable', 'Romaine lettuce hearts Class I', 'lettuce', 3);
insert into item (name, price, rating, category, description, imagepath, store_id) values ('Lamb Leg 2.5kg', 20, 4, 'Meat', 'Bone in whole leg of lamb', 'lamb', 2);
insert into item (name, price, rating, category, description, imagepath, store_id) values ('Fresh Chicken Skin on Drumsticks 1kg', 5, 2, 'Meat', 'Fresh class A bone in skin on chicken drumsticks', 'drumsticks', 2);
insert into item (name, price, rating, category, description, imagepath, store_id) values ('Fresh Chicken Breast Fillets', 5.99, 4, 'Meat', 'Fresh class A chicken breast fillets skinless and boneless', 'chickenbreast', 2);
insert into item (name, price, rating, category, description, imagepath, store_id) values ('Lamb Liver', 2.13, 4, 'Meat', '450g Lamb Liver', 'liver', 2);
insert into item (name, price, rating, category, description, imagepath, store_id) values ('Beef Sirloin Steak', 5, 4, 'Meat', 'British beef sirloin steak', 'steak', 2);
insert into item (name, price, rating, category, description, imagepath, store_id) values ('Prawn- Peeled And Cooked 250g', 4, 3, 'Meat', 'Individually quick frozen cooked and peeled cold water prawns in a protective ice glaze', 'prawn', 3);
insert into item (name, price, rating, category, description, imagepath, store_id) values ('Loch Trout Fillets', 4.5, 3, 'Meat', '2 boneless Scottish loch trout fillets', 'fish', 1);
insert into item (name, price, rating, category, description, imagepath, store_id) values ('British Chicken Thighs 1KG', 2.6, 3, 'Meat', 'Fresh class A bone in skin on chicken thighs', 'chickthighs', 3);
INSERT INTO item (name, price, rating, category, description, imagepath, store_id) VALUES ('Gilette Razor' ,  3.5, 3, 'Toiletries', 'Less Razor burn vs. BlueII without lubrastrip', 'razor', 2);
INSERT INTO item (name, price, rating, category, description, imagepath, store_id) VALUES ('Sure Deodorant', 1.75, 5, 'Toiletries','Sure Active Dry Anti-perspirant Deodorant Aerosol 250 ml has been developed to give you cutting-edge protection from sweat and odour', 'deodorant', 3);
INSERT INTO item (name, price, rating, category, description, imagepath, store_id) VALUES ('Colgate Total', 2.5, 4, 'Toiletries', 'Just a toothpaste', 'toothpaste', 3);
INSERT INTO item (name, price, rating, category, description, imagepath, store_id) VALUES ('Domestos Bleach', 1, 5, 'Toiletries', 'Domestos Original Thick Bleach eliminates all known germs', 'bleach', 1);
insert into item (name, price, rating, category, description, imagepath, store_id) values ('Tampax Tampon', 2.35, 4, 'Toiletries', 'Tampax’s N°1 combination of comfort, protection and discretion', 'tampon', 2);
insert into item (name, price, rating, category, description, imagepath, store_id) values ('Imperial Leather Moisturising', 2.1, 3, 'Toiletries', 'Master Perfumers Since 1921', 'imperial', 2);
insert into item (name, price, rating, category, description, imagepath, store_id) values ('Carex Hand Wash', 1.25, 2, 'Toiletries', 'Kills 99.9% of Bacteria', 'handwash', 2);
insert into item (name, price, rating, category, description, imagepath, store_id) values ('Nicky Toilet Tissue 32 Rolls', 8.5, 3, 'Toiletries', 'Nicky Soft Touch is a gentle toilet tissue, offering the skin additional comfort', 'tissue', 1);
INSERT INTO item (name, price, rating, category, description, imagepath, store_id) VALUES ('Bassetts MultiVitamins', 5.5, 3, 'WellBeing', 'Raspberry & Pomegranate flavoured multivitamin food supplement pastilles with sweeteners.', 'vitamins', 2);
INSERT INTO item (name, price, rating, category, description, imagepath, store_id) VALUES ('Paracetamol', 0.5, 4, 'WellBeing', 'Effective pain relief', 'tablets', 1);
INSERT INTO item (name, price, rating, category, description, imagepath, store_id) VALUES ('Aveeno Cream', 1.5, 2, 'WellBeing', 'Moisturise your dry face', 'cream', 3);


