INSERT INTO store (name, opening, closing, location, review) VALUES ('Parachute', 6, 1, 'Hammersmith', 'Poor');
INSERT INTO store (name, opening, closing, location, review) VALUES ('One Pound Store' , 7, 23, 'White City', 'Good');
INSERT INTO store (name, opening, closing, location, review) VALUES ('Ealing Food and Wine', 18, 7, 'Ealing', 'Satisfactory');

INSERT INTO item (name, price, rating, category, description, store_id) VALUES ('Coca Cola', 0.99, 5, 'Drink', 'soda', 2);
INSERT INTO item (name, price, rating, category, description, store_id) VALUES ('Tea', 1, 5, 'Drink', 'Best for sleepless time', 1);
INSERT INTO item (name, price, rating, category, description, store_id) VALUES ('Coffee', 8, 5, 'Drink', 'the best coffee you can find in corner store', 3);
INSERT INTO item (name, price, rating, category, description, store_id) VALUES ('Large Milk', 1.60, 4, 'Dairy', 'not sustainable', 2);
INSERT INTO item (name, price, rating, category, description, store_id) VALUES ('Butter', 1.60, 4, 'Dairy', 'not sustainable', 3);
INSERT INTO item (name, price, rating, category, description, store_id) VALUES ('Mouldy Cheese', 1.60, 4, 'Dairy', 'very stinky', 1);
INSERT INTO item (name, price, rating, category, description, store_id) VALUES ('Bread', 0.6, 1, 'Bakery', 'Really bad bread', 2);
INSERT INTO item (name, price, rating, category, description, store_id) VALUES ('Cinnamon roll', 0.6, 2, 'Bakery', 'Really bad bread', 1);
INSERT INTO item (name, price, rating, category, description, store_id) VALUES ('Baguette', 0.6, 2, 'Bakery', 'Really bad bread', 1);
INSERT INTO item (name, price, rating, category, description, store_id) VALUES ('Donut', 0.6, 2, 'Bakery', 'Really bad bread', 3);
INSERT INTO item (name, price, rating, category, description, store_id) VALUES ('Razor' ,  6, 4, 'Toiletries', 'really sharp razors', 2);
INSERT INTO item (name, price, rating, category, description, store_id) VALUES ('Sure Deodrant', 3, 5, 'Toiletries','Get the job done', 3);
INSERT INTO item (name, price, rating, category, description, store_id) VALUES ('Toothpaste', 4, 4, 'Toiletries', 'Just a toothpaste', 3);
INSERT INTO item (name, price, rating, category, description, store_id) VALUES ('Bleach', 1, 5, 'Toiletries', 'Dont drink it if you are tyring to die', 1);
INSERT INTO item (name, price, rating, category, description, store_id) VALUES ('MultiVitamines', 10, 3, 'WellBeing', 'provides 1000 types of vitamines', 2);
INSERT INTO item (name, price, rating, category, description, store_id) VALUES ('Asprin', 0.3, 2, 'WellBeing', 'Only effective for toothache', 1);
INSERT INTO item (name, price, rating, category, description, store_id) VALUES ('Face cream', 0.3, 2, 'WellBeing', 'Moisturise your dry face', 3);
insert into item (name, price, rating, category, description, store_id) values ('Cheese - Brie, Triple Creme', 23.63, 2, 'Dairy', 'Vivamus vel nulla eget eros elementum pellentesque.', 3);
insert into item (name, price, rating, category, description, store_id) values ('Milk 2% 500 Ml', 3.64, 1, 'Dairy', 'Quisque porta volutpat erat.', 1);
insert into item (name, price, rating, category, description, store_id) values ('Water - Tonic', 19.7, 1, 'Drink', 'Praesent id massa id nisl venenatis lacinia.', 3);
insert into item (name, price, rating, category, description, store_id) values ('Quail - Whole, Bone - In', 10.2, 5, 'Meat', 'Praesent blandit.', 3);
insert into item (name, price, rating, category, description, store_id) values ('Sprouts - Bean', 2.18, 3, 'Vegetable', 'Morbi ut odio.', 2);
insert into item (name, price, rating, category, description, store_id) values ('Shrimp - 21/25, Peel And Deviened', 20.1, 3, 'Meat', 'Praesent blandit.', 3);
insert into item (name, price, rating, category, description, store_id) values ('Fiddlehead - Frozen', 2.81, 3, 'Vegetable', 'Nullam molestie nibh in lectus.', 2);
insert into item (name, price, rating, category, description, store_id) values ('Beans - Kidney, Red Dry', 22.12, 3, 'Vegetable', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 2);
insert into item (name, price, rating, category, description, store_id) values ('Napkin White - Starched', 23.61, 3, 'Toiletry', 'In congue.', 1);
insert into item (name, price, rating, category, description, store_id) values ('Monkfish Fresh - Skin Off', 3.32, 3, 'Meat', 'Nulla nisl.', 1);
insert into item (name, price, rating, category, description, store_id) values ('Bread Country Roll', 3.79, 4, 'Bakery', 'Nunc purus.', 1);
insert into item (name, price, rating, category, description, store_id) values ('Banana Turning', 28.45, 4, 'Fruit', 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 3);
insert into item (name, price, rating, category, description, store_id) values ('Pear - Halves', 13.42, 3, 'Fruit', 'Sed ante.', 1);
insert into item (name, price, rating, category, description, store_id) values ('Beef - Top Sirloin', 29.92, 4, 'Meat', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.', 2);
insert into item (name, price, rating, category, description, store_id) values ('Bread - Pita', 8.83, 3, 'Bakery', 'Pellentesque at nulla.', 2);
insert into item (name, price, rating, category, description, store_id) values ('Wine - Alsace Gewurztraminer', 16.68, 3, 'Drink', 'Pellentesque at nulla.', 2);
insert into item (name, price, rating, category, description, store_id) values ('Sugar - Brown, Individual', 24.8, 3, 'HomeEssentia', 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 3);


